version: "3.8"

services:
  babylon-upload-bot-js:
    build: .
    container_name: babylon-upload-bot-js
    command: node /app/anchor-bot/index.js
    volumes:
      - ./anchor-bot/logs:/app/anchor-bot/logs
    env_file: .env
    network_mode: "host"
    restart: unless-stopped
